### ISSUE TITLE
Information on scoring polls can be improved

### ISSUE THREAD

**Issue by javiexin** [Wolfsblvt/advancedpolls#58]
When showing voters on scoring and multivalued polls, more information can be shown (number of voters, number of votes per voter, etc.) both for regular users and for mods.

**Comment by Wolfsblvt** [comment]
Isn't that an enhacement? What's the bug here?

**Comment by javiexin** [comment]
Yes, I was precisely reviewing that... I had a number of things I have seen, and was tracking them all.

**Comment by Wolfsblvt** [comment]
Yeah, no problem. Good to see that you are working also on such issues (:
Oh, when your are doing a bunch of things like cleaning ab, reworking some behavior, can you mabe see if you can break up the logic into smaller methods wherever you can and where it makes sense?
Like creating a controller, wich handles stuff, etc. Dunno how much you are into this object orientated things.
Otherwise, just keep it. That kind of refactoring is something that can be done far in the future, when all features are done and tested, etc etc.

**Comment by javiexin** [comment]
Agreed, I am looking at completing the functionality first.  As for controllers, or other kinds of objects/classes, yeah, we'll do it later on :).  But if I have a chance, I will be starting to do it.
For example, it may make sense to create a "poll" controller, storing and accessing all poll votes, a "vote" controller that will verify the process of voting, a "visibility" controller to have all potential ways to access the poll (much like in the MVC - model, view, controller - paradigm).  I will look into it, but later.

**Comment by Wolfsblvt** [comment]
The best is to make as much OO as possible. Code that needs to be copypasted cause of phpBB should be in an own method, and calling a controller/some OOP method, so that it can easily be replaced in the future.
